export const tabItems = [
    {
        image: '/assets/img/Movies/DC-logo.jpg',
        title: 'DC',
        text: '<p><b>Marve</b> Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quidem, totam. Assumenda saepe fugit qui officiis ducimus libero incidunt consequatur deleniti, iste quod velit quaerat? Reprehenderit, exercitationem sint. Illum, molestias odit! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quidem, totam. Assumenda saepe fugit qui officiis ducimus libero incidunt consequatur deleniti, iste quod velit quaerat? Reprehenderit, exercitationem sint. Illum, molestias odit! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quidem, totam. Assumenda saepe fugit qui officiis ducimus libero incidunt consequatur deleniti, iste quod velit quaerat? Reprehenderit, exercitationem sint. Illum, molestias odit!</p> <p>About Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quidem, totam. Assumenda saepe fugit qui officiis ducimus libero incidunt consequatur deleniti, iste quod velit quaerat? Reprehenderit, exercitationem sint. Illum, molestias odit! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quidem, totam. Assumenda saepe fugit qui officiis ducimus libero incidunt consequatur deleniti, iste quod velit quaerat? Reprehenderit, exercitationem sint. Illum, molestias odit! Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quidem, totam. Assumenda saepe fugit qui officiis ducimus libero incidunt consequatur deleniti, iste quod velit quaerat? Reprehenderit, exercitationem sint. Illum, molestias odit!</p>',
    },
    {
        image: '/assets/img/Movies/Marvel-Logo.jpeg',
        title: 'Marvel',
        text: '<p>Though the concept of a shared universe was not new or unique to comic books in 1961, writer/editor Stan Lee, together with several artists including Jack Kirby and Steve Ditko, created a series of titles where events in one book would have repercussions in another title and serialized stories would show characters\' growth and change. Headline characters in one title would make cameos or guest appearances in other books. Eventually, many of the leading heroes assembled into a team known as the Avengers. </p><p>This was not the first time that Marvel\'s characters had interacted with one another—Namor the Sub-Mariner and the original Human Torch had been rivals when Marvel was Timely Comics (Marvel Vault)— but it was the first time that the comic book publisher\'s characters seemed to share a world. </p><p>The Marvel Universe was also notable for setting its central titles in New York City; by contrast, many DC heroes live in fictional cities. Care was taken to portray the city and the world as realistically as possible, with the presence of superhumans affecting the common citizens in various ways.</p>',
    },
];